### ISSUE TITLE
Multi Threading | Sidekiq

### ISSUE THREAD

**Issue by ivanacostarubio** [adelevie/parse-ruby-client#104]
Hi! 

I am in the same situation as https://github.com/adelevie/parse-ruby-client/issues/98

I've been running some code single threaded for a few months without any problems. That code calls Parse::Push. Recently, we move some of that code to use http://sidekiq.org/ and we are seeing some error for the first time. They are:

```ruby
Parse::ParseProtocolError: : unauthorized
Patron::HostResolutionError
Patron::URLFormatError
```

Not sure if all the exceptions are related to thread safety. I'll investigate further.

I am not a thread safety expert, but I would love to collaborate on making this gem thread safe. At least, the push notifications part. :smile:

A quick peak into the code reveals: 

https://github.com/adelevie/parse-ruby-client/blob/master/lib/parse/client.rb#L183

Is a singleton needed for the client?

**Comment by rhymes** [comment]
Can you guys please take a look at #165 ?
