### ISSUE TITLE
multiple conditions on same field clobber each other instead of combining

### ISSUE THREAD

**Issue by ericcj** [adelevie/parse-ruby-client#110]
if i do:

query.eq('arrayField', 1)
query.not_eq('arrayField', 2)

the query sent is "where"=>"{"arrayField":{"$ne":2}}} without any mention of the equality condition.  this is clearly wrong, but also a big breaking api change when we fix it

**Comment by rhymes** [comment]
@ericcj You can't have an eq and a not_eq at the same time on the same field. Not even Parse supports that.
