### ISSUE TITLE
Add relation throws exception from parse

### ISSUE THREAD

**Issue by styrken** [adelevie/parse-ruby-client#111]
Hello,

I'am doing the following:

newMovie = Parse::Object.new("movie")
newMovie.array_add_relation("regions", regionObj.pointer)
newMovie.save

error: invalid type for key regions, expected relation<region>, but got array (Parse::ParseProtocolError)

I'am using the "Relation" datafield in parse.. is that wrong?

version: 0.2.0

**Comment by arcticleo** [comment]
I have the same issue. Can anybody add relations?

**Comment by arcticleo** [comment]
Ah, Relation is meant for many-to-many relationships, however what I wanted in my case is a one-to-many, which should use the Pointer data type to point to the parent.

**Comment by rhymes** [comment]
@arcticleo it works also with one to many. Can you post the code?

```
region = @client.object('Region', nil)
region.save

movie = @client.object('Movie', nil)
movie.save

movie.array_add_relation('regions', region.pointer)
movie.save
````

this works
