### ISSUE TITLE
Calculate total count of _User data using parse_ruby_client 

### ISSUE THREAD

**Issue by aditya-mandal** [adelevie/parse-ruby-client#112]
Hi All,

I am using parse_ruby_client gem for Parse API calls.

In below rails code i want to calculate total count of users data, but it doesn't works. Please help me.

```
def total_count
    Parse.init :application_id => Rails.application.config.parse_application_id, :api_key => Rails.application.config.parse_api_key

    # build a query on the User class
    object_query_count = Parse::Query.new("_User")
    # no limit on the results
    object_query_count.limit = 0
    # check to make sure the email is not blank
    object_query_count.exists("email")
    # get the count
    object_query_count.count
    # store the count
    count = object_query_count.get["count"]
    # print the count
    Rails.logger.info "Total with Email: #{count}"
    # calculate how many iterations are needed to go through all the records

    redirect_to root_path 
  end
```

**Comment by Xavdidtheshadow** [comment]
@aditya-mandal 

I believe setting `limit == 0` means you return 0 results.

Also, ruby hash (what is returned by a query object where `count == true`) has no `#get` function (unlike python's `dict`). Instead, just use `object_query_count['count']`, which returns a number.

Note that if you've got 1000 > users > 100, you should set your limit to the max (1000). If you've got > 1000 users, you'll have to page through results. 

Does that make sense?
