### ISSUE TITLE
make tests work offline

### ISSUE THREAD

**Issue by ericcj** [adelevie/parse-ruby-client#125]
it's pretty close to using VCR in all tests now and would be desirable to not need a parse api key to run tests so we should ensure all tests use VCR and maybe even add a travis build matrix with no env variables set to ensure it stays that way.

problematic ones like test_or which runs the same query twice and expects different results fail under VCR, so it should just be split into two tests.  others that actually hit the parse api like user signup and password reset just shouldn't...we should make vcr work with them if it doesn't by default

**Comment by Xavdidtheshadow** [comment]
This can be done by telling VCR to match path+hostname instead of URI. I'll get to this.

**Comment by rhymes** [comment]
This should be fixed when we merge #174

**Comment by rhymes** [comment]
All tests now run offline.

**Comment by Xavdidtheshadow** [comment]
Awesome! Great job!






~DB
