### ISSUE TITLE
How to get the most recent record of a given class from parse?

### ISSUE THREAD

**Issue by dlio** [adelevie/parse-ruby-client#128]
Is there an easy lookup to simply retrieve the one most recently created record for a given class? I have been trying various workarounds with the example methods but I cannot seem to figure out how. I could use the HTTP API to do so but I'm guessing that this is a fairly common use case for this gem. Any help would be much appreciated; cheers and thanks for this great gem.

I see a proposed solution in the TODO queries but nothing that seems currently viable.
Is the only way for me to do this to use a different gem to interact directly with parse via HTTP requests manually?

see also: https://github.com/adelevie/parse_resource/issues/127

**Comment by rhymes** [comment]
@dlio if you track the github version of the gem you can issue most of the queries and get the most recently created, for example:

```
objects = client.query('YourClass').tap do |q|
    q.order_by = 'createdAt'
    q.order = :descending
end.get
```

HTH
