### ISSUE TITLE
InvalidComponentError in authenticating when password contains backticks

### ISSUE THREAD

**Issue by sent-hil** [adelevie/parse-ruby-client#131]
```
#<URI::InvalidComponentError: bad component(expected query component): username=sent-hil&password=`1234567890-=>
```

I believe it's the back ticks that's the problem.

**Comment by Xavdidtheshadow** [comment]
@sent-hil did you figure this out? what was the resolution?

**Comment by sent-hil** [comment]
Don't think I ever did. Closed it since I was cleaning up my issues and removing ones that haven't activity in a long time.

**Comment by Xavdidtheshadow** [comment]
oh, got it. I didn't realize how old this was. sorry!
