### ISSUE TITLE
Multiple clients to send Push to multiple Parse Apps?

### ISSUE THREAD

**Issue by dominostars** [adelevie/parse-ruby-client#159]
I need to send push notifications to two different parse apps, is this possible to do? Would something like this produce unexpected behavior or side effects that I should know about?

Parse.Init API_KEY_1
Parse.Push 
Parse.Init API_KEY_2
Parse.Push

**Comment by Xavdidtheshadow** [comment]
@dominostars sorry about the slow response. 

Because the client is module-level, you can only have one at a time. but, calling `Parse.init` again with a new api key/secret is safe.

**Comment by Xavdidtheshadow** [comment]
see #165, this is possible in dev and will be available in prod soonish
