### ISSUE TITLE
TypeError Exception: no implicit conversion of Pathname into String when i make a get query

### ISSUE THREAD

**Issue by aamishiftikhar** [adelevie/parse-ruby-client#161]
In my controller method, i am doing this

def update_item_category
    Parse.init :application_id => "appid",
               :api_key        => "appkey",
               :quiet           => true
    puts Parse::Query.new("Brands").eq("brand_id", "5").get
  end

on ".get" i am getting "TypeError Exception: no implicit conversion of Pathname into String".
Please help me out.

**Comment by Datise** [comment]
What's your stack trace look like? I have been working with this gem recently and seem to remember an error like this.

**Comment by rhymes** [comment]
@aamishiftikhar do you still have this problem? Can you provide more information?
