### ISSUE TITLE
undefined method 'get' for Parse::Installation:Class

### ISSUE THREAD

**Issue by origds** [adelevie/parse-ruby-client#162]
I am using 

installation = Parse::Installation.get "objectId"

as said in the tutorial. It worked but now I am getting this error. 
I don't know what's going on with this. 

Anyone have any idea?

**Comment by rhymes** [comment]
Hi @origds, can you give more info about that? Which version of parse-ruby-client are you using? Did you manage to fix it?

**Comment by origds** [comment]
I am using parse-ruby-client 0.3.0. I don't have more details about the error. I just follow the gem documentation, and it worked. But now I am getting the error: undefined method 'get' for Parse::Installation:Class

**Comment by rhymes** [comment]
@origds parse-ruby-client 0.3.0 doesn't have that method. You need to use the github version. 

Replace your entry in the `Gemfile` with

```
gem 'parse-ruby-client', git: 'https://github.com/adelevie/parse-ruby-client.git'
```

there will likely be some differences, so check the documentation if you're having further problems.

**Comment by origds** [comment]
Thank you! :+1: @rhymes

**Comment by origds** [comment]
I still have the problem, change the Gemfile and updated it, but I still have version 0.3.0

**Comment by rhymes** [comment]
Can you post your Gemfile and Gemfile.lock? Or you can just remove your Gemfile.lock and then run `bundle install`

btw @origds can you please not open a issue for the same problem :) ?

**Comment by MarkMurphy** [comment]
I'm having this problem too, I have the master branch installed, I'm trying to assign a custom key named 'alias' and I'm getting the following error:

```
undefined method 'alias' for Parse::Installation:Class
```

**Comment by rhymes** [comment]
@MarkMurphy this is not the same problem as the op though. 

Only the default (see https://parse.com/docs/rest/guide/#push-notifications-uploading-installation-data) fields have attribute accessors, for the rest you have to you take advantage of the fact the Installation object is a Hash, so:

```ruby
installation = parse.installation.tap do |i|
  i.device_token = device_token["device_token"]
  i.device_type = "ios"
  i.channels = device_token["tags"]
  i["alias"] = device_token["alias"]
end
```

**Comment by MarkMurphy** [comment]
gotcha, thanks
