### ISSUE TITLE
Retrieving all rows including specific user_objectId

### ISSUE THREAD

**Issue by akinori5** [adelevie/parse-ruby-client#175]
records = Parse::Query.new("Record").tap do |q|
 q.eq("user", user_objectId) 
records.get

I got the error bellow.
`process_response': 102: pointer field user needs a pointer value (Parse::ParseProtocolError)

Yes. I understand this because user column of "Record" is pointer<_User> type.
Then how can I write the query so that I can retrieve all the rows including specific user_objectId?

Thanks

**Comment by rhymes** [comment]
What's user_objectId ? A string?

I guess you need something like this:

```
records = Parse::Query.new("Record").tap do |q|
  q.eq('user', Parse::Pointer.new({"className" => "_User", "objectId" => user_objectId}
end.get
```

**Comment by rhymes** [comment]
@Xavdidtheshadow @adelevie these are not bugs and shouldn't be on the issues list. maybe we should setup a mailing list or something?

**Comment by akinori5** [comment]
Thanks it worked perfect!! Thank you so much for your quick answer. It saved lots of time.
Also this parse-ruby client gem speeds up my development.

As you mentioned, it would be great to have mailing list or discussion board for the gem. It is true that I felt it was not appropriate to ask such a question on github issue.

Thanks

**Comment by rhymes** [comment]
@akinori5 hopefully the 1.0 is going to come out soon, we might setup a mailing list before then. In the meantime, keep on opening issues ;-)
