### ISSUE TITLE
Leaks Faraday errors

### ISSUE THREAD

**Issue by henrik** [adelevie/parse-ruby-client#182]
We're on 0.3.0. Haven't looked if this is changed in master.

We sometimes have to handle errors like Faraday::Error::ConnectionFailed and Faraday::Error::TimeoutError from the Parse lib – would be great if the Faraday dependency was encapsulated in that respect, and we got `Parse::Error` or something instead.

**Comment by rhymes** [comment]
@henrik good point, it's the same in master. Can you work on a PR for it ?

**Comment by henrik** [comment]
Sure, I'll give it a quick shot :)

**Comment by marioacarvalho** [comment]
I'm getting this error 

```
Retrying Parse Error #<Faraday::TimeoutError> on request https://api.parse.com/1/push 
```

It's related?
