### ISSUE TITLE
Can't save a Parse file if local_filename has a space

### ISSUE THREAD

**Issue by tra38** [adelevie/parse-ruby-client#192]
This issue can be resolved IF you use URI.escape on the filename. For example
```ruby
:local_filename => URI.escape("hello world.txt")
```
But this solution seems so inelegant. It would be preferable if the library itself does the "URI escape" instead of the server-side algorithm.

**Comment by Xavdidtheshadow** [comment]
This would be reasonable. Is there a situation that this would break people's existing code?

**Comment by rhymes** [comment]
I understand your point @tra38 but changing this behavior might break existing code in which the caller already escapes the file name and that would result in a double escape. We could put a flag with by default does not escape but it kind of defeat the purpose for elegance. 

I'm going to close this.
