### ISSUE TITLE
undefined method `create' for Parse:Module

### ISSUE THREAD

**Issue by torasakura** [adelevie/parse-ruby-client#193]
when i try to initialize Parse with Parse.create i always get `undefined method 'create' for Parse:Module`

**Comment by Xavdidtheshadow** [comment]
@torasakura does your gemfile specify the git repository instead of the rubygems version?

**Comment by torasakura** [comment]
ah sorry i should read carefully. i used the rubygems version, now it is working. thanks for pointing me in the right direction.
