### ISSUE TITLE
Query for keys in a key that is an object

### ISSUE THREAD

**Issue by Datise** [adelevie/parse-ruby-client#196]
I have been using this gem for months now (thanks everybody) but am at a total loss at the moment.
I have a column in one of my tables that is an object (probably should have been an array but it's too late for that now) and I want to return records where the object has a key(s). ex:
Table: Pictures
Column: Colors
colors = {"1": 3, "2": 4}
colors = {"2": 3, "4": 4}
colors = {"9": 3, "15": 4}

find Pictures records where Colors has the key of "2" (and/or  "2" or  "4")
Suggestions?

**Comment by rhymes** [comment]
Not sure you can do that. These are the operators you can use on columns https://github.com/adelevie/parse-ruby-client/blob/master/README.md#query-contraints and this is what you can do with relational queries https://github.com/adelevie/parse-ruby-client/blob/master/README.md#relational-queries

You can query relations or specific fields but there doesn't seem to be any operator for "check the value of a field which is a hash and see if any of these keys are present" in the Parse REST guide https://parse.com/docs/rest/guide

**Comment by Datise** [comment]
Yea after spending more than a little while reading both docks I didn't think it was possible either. Scaffolded the table months ago without checking that the functionality exists (go me...heh). Might have to spin up a little no sql and web hook for consistency lol. 
It's a little frustrating that you can save data as a hash format but can't traverse that data afterwards. Why not obligate other data formats for storage from the start. Regardless thanks for your answer.
