### ISSUE TITLE
How to initialize Parse key

### ISSUE THREAD

**Issue by llvc** [adelevie/parse-ruby-client#200]
Hi sir
I don't know where to put the following code.

Parse.init application_id: APPLICATION_ID,
api_key: API_KEY,
quiet: false

Thanks.

**Comment by FructuosoRobles** [comment]
check this out 

http://stackoverflow.com/questions/25086303/if-i-require-a-file-in-application-rb-does-this-make-it-available-throughout-the

**Comment by Xavdidtheshadow** [comment]
You can put it anywhere that gets run before you want to access parse. Probably next to whatever other config you're doing. Hard to provide a more specific answer without code.

**Comment by llvc** [comment]
Thanks
I could solve the problem
