### ISSUE TITLE
Parse Retirement

### ISSUE THREAD

**Issue by dcdspace** [adelevie/parse-ruby-client#201]
Will this gem continue to work with the announcement of the retirement of Parse and its migration to the new Parse Server?

**Comment by rhymes** [comment]
I do not know for now honestly. It depends on how compatible the migration plan they have will be with the current Parse API. Maybe all it takes is to allow the user to customize the Parse API endpoint and use its own server, maybe not. As of today also Push is not supported.

**Comment by Xavdidtheshadow** [comment]
Yeah, it depends on what the stable state of the new parse server's development looks like. If it's the soft of things we could design a stable gem against, then we can do a major version release and go from there. Time will tell!

**Comment by jameslin101** [comment]
I've been able to migrate to my own parse server.
Just add these lines to your environment files
    Parse::Protocol.instance_eval {remove_const :HOST} if defined?(Parse::Protocol::HOST)
    Parse::Protocol.const_set(:HOST, 'hosted-parse-server.com')

**Comment by rhymes** [comment]
@jameslin101 you should be able to pass "host" to Parse.create and provide your hostname, try like this:

```
client = Parse.create host: 'hosted-parse-server.com'
```

**Comment by dcdspace** [comment]
I tried doing that @jameslin101 but it isn't working.

**Comment by dcdspace** [comment]
The issue is that the version is still pointing to the `/1/` that was in the original Parse, but it is now custom. Is there an easy way to change the version number?

**Comment by rhymes** [comment]
@dcdspace there's a failing PR about that https://github.com/adelevie/parse-ruby-client/pull/202 - still have to take a look

**Comment by taijizhu** [comment]
Try following lines, the idea is to replace constant set in Protocol.  You need to do it for any constant that has VERSION preset.  My parseMount variable has the customized parse mount location.  

Parse::Protocol.instance_eval {remove_const :VERSION} if defined?(Parse::Protocol::VERSION)
      Parse::Protocol.const_set(:VERSION, "#{parseMount}")
 
Parse::Protocol.instance_eval {remove_const :USER_LOGIN_URI} if defined?(Parse::Protocol::USER_LOGIN_URI)
      Parse::Protocol.const_set(:USER_LOGIN_URI, "/#{parseMount}/login")

**Comment by rhymes** [comment]
@dcdspace @taijizhu it should be fixed by https://github.com/adelevie/parse-ruby-client/commit/d6e29fa9a752b4cbcc680151669fc83c615b32be

**Comment by taijizhu** [comment]
thanks

**Comment by dcdspace** [comment]
Thanks. Would it be possible to add the new version to RubyGems for easy installation?
