### ISSUE TITLE
Can't use github master version

### ISSUE THREAD

**Issue by patwhitehead1** [adelevie/parse-ruby-client#204]
Trying to use the master version, running into this error:

/Users/Patrick/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- parse-ruby-client (LoadError)
	from /Users/Patrick/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from app.rb:1:in `<main>'

This is my Gemfile:

source 'https://rubygems.org'
gem 'sinatra'
gem 'parse-ruby-client', git: 'https://github.com/adelevie/parse-ruby-client.git'

Any idea what could be causing the problem?

**Comment by rhymes** [comment]
@patwhitehead1 what's in your app.rb at line 1?

**Comment by Xavdidtheshadow** [comment]
Additionally, what command are you using to run your code?

**Comment by patwhitehead1** [comment]
This is all I have in app.rb:

```
require 'sinatra'
require 'parse-ruby-client'

get '/hi' do
  "Hello World!"
end
```


And I'm running it with ruby app.rb

**Comment by patwhitehead1** [comment]
This seems to work when I run it with:

`bundle exec ruby app.rb`

**Comment by rhymes** [comment]
@patwhitehead1 yes, you need to execute with bundle. See http://bundler.io/v1.11/bundle_exec.html

```
This command executes the command, making all gems specified in the Gemfile(5) available to require in Ruby programs.
```
