### ISSUE TITLE
unable to create client from console

### ISSUE THREAD

**Issue by jameslin101** [adelevie/parse-ruby-client#207]
When I try to create a client 
``
client = Parse.create(:application_id => "someappid",
                      :api_key        => "somekey",
                      :host           => "https://someapp.herokuapp.com")
``
I end up getting this

``
#<Parse::Client:0x007fb58d548a90 @host="https://someapp.herokuapp.com", @path="/1", @application_id="someappid", @api_key="somekey", @master_key=nil, @session_token=nil, @max_retries=3, @logger=#<Logger:0x007fb58d5489c8 @progname=nil, @level=1, @default_formatter=#<Logger::Formatter:0x007fb58d548928 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x007fb58d548838 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:/dev/ttys010>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x007fb58d548680 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007fb58d5481a8>>>>, @quiet=false, @timeout=30, @interval=0.5, @backoff_factor=2, @retried_exceptions=["Faraday::Error::TimeoutError", "Faraday::Error::ParsingError", "Faraday::Error::ConnectionFailed", "Parse::ParseProtocolRetry"], @session=#<Faraday::Connection:0x007fb58e21e530 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions timeout=30, open_timeout=30>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fb58e21c938 @handlers=[FaradayMiddleware::EncodeJson, Faraday::GetMethodOverride, Faraday::BetterRetry, Faraday::ExtendedParseJson, Faraday::Response::Logger, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTPS:0x007fb58e21c1e0 URL:https://someapp.herokuapp.com/>, @proxy=nil>> 
``

**Comment by Xavdidtheshadow** [comment]
@jameslin101 did you figure it out?
