### ISSUE TITLE
Remove support for Ruby 1.9 and 2.0

### ISSUE THREAD

**Issue by rhymes** [adelevie/parse-ruby-client#212]
1.9.3 is EOL since February 23, 2015 https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

2.0 is EOL since February 24, 2016 https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

I think we should stop testing against them.

I don't actively follow JRuby development but we should probably stop supporting JRuby 1.7 as well since it's based on Ruby 1.9

**Comment by xavdid** [comment]
Agree! I'm not sure if there's any code changes to be made to ensure the gem _isn't_ backwards compatible, but I can make a note in the readme (and edit travis.yml accordingly) about it not being tested on old versions and only being officially supported on >= 2.1

**Comment by rhymes** [comment]
@xavdid no, luckily we don't have to change anything. We just need to tell gemspec >= 2.1, remove the old versions from travis and specify the new minimum supported version in the README as you rightly suggest. Thanks!

**Comment by rhymes** [comment]
We should also bump the lib version for this change.

**Comment by rhymes** [comment]
https://github.com/adelevie/parse-ruby-client/commit/e17ac4f93a74eee4acaa0cf7f66c0d31eac88780
