### ISSUE TITLE
Running with local parse server

### ISSUE THREAD

**Issue by ivansifrim** [adelevie/parse-ruby-client#214]
Hello,

I'm trying to run a script with this gem to operate on my local parse server (http://localhost:1337/parse) 

I'm using the master branch because I didn't see a way to include a server url in the previous version. 

Parse.create :application_id      => "xxx",
:master_key          => "xxx",
:host                => 'http://localhost:1337',
:path                => '/parse'

Then I try: 

me = Parse::User.authenticate("username", "password")

but it breaks with the error: uninitialized class variable @@client in Parse

Any help would be appreciated. Thank you!

**Comment by rhymes** [comment]
@ivansifrim you have to pass along the client you just created:

client = Parse.create ...
me = Parse::User.authenticate("username", "password", client)

**Comment by ivansifrim** [comment]
This worked - thanks!
