### ISSUE TITLE
back4app URL

### ISSUE THREAD

**Issue by maximbilan** [adelevie/parse-ruby-client#216]
Hi, I've migrated my **Parse** project to **Back4App** service.
And I need to update host for this:

`http://parseapi.back4app.com`

So, I've added parameter _:host_ to initialization:

`Parse.init :application_id => "some key", :master_key     => "some key", :host => "parseapi.back4app.com"`

But unfortunately I got the _404_ error during the request:

`INFO -- : Parse query for /1/installations {"where"=>"{}", :count=>true, :limit=>0}
  INFO -- : get https://parseapi.back4app.com/1/installations?count=true&limit=0&where=%7B%7D
  INFO -- Status: 404`

What I do wrong? Could you help me?

I use 0.3.0 version.

Thanks.

**Comment by xavdid** [comment]
when you're logged in, does https://parseapi.back4app.com/1/installations?count=true&limit=0&where=%7B%7D return anything for you? I'm getting Unauthorized, but that makes sense.

**Comment by maximbilan** [comment]
When I logging, I've got the same _404_ error:

```
INFO -- : get https://parseapi.back4app.com/1/login?password=123&username=duracell%40email.com
INFO -- Status: 404
```

Using the next code:

`user = Parse::User.authenticate("duracell@email.com", "123")`

**Comment by xavdid** [comment]
Is there something that ties your app to that URL? `https://parseapi.back4app.com/1/login` doesn't seem to be specific to you unless you got really lucky with that subdomain. 

Also, I'm not sure that host works properly for the version on rubygems, (`0.3.0`) and I'd recommend pointing your gemfile to a specific commit on the master branch instead. 

Lastly, I don't think you can `GET /login`- that's a `POST` endpoint. So that might be part of the problem too.

**Comment by maximbilan** [comment]
I've migrated my data from Parse to Back4App service and the only one thing I should to do after the migration, it's to update API URL to new service. If I used my old url: api.parse.com , all is ok. And in my iOS application all work good with the both urls.

Ok, I will try to use the latest version of this client. Could you give reference or manual how I can do this? I'm a not expert in Ruby, so unfortunately a lot of things with gems, etc hard to understand for now. Thanks.

**Comment by rhymes** [comment]
@maximbilan maybe you should also direct the question to Back4App customer service, it seems you're either using the wrong URL or there's an issue on their servers.

BTW, to upgrade to the 1.0alpha version you need to open your Gemfile and replace your line:

```ruby
gem 'parse-ruby-client'
```

with

```ruby
gem 'parse-ruby-client', git: 'https://github.com/adelevie/parse-ruby-client.git'
```

In addition you have to change the way you use the library, according to the https://github.com/adelevie/parse-ruby-client/blob/master/README.md

I would suggest you to figure out which is the correct URL before anything else.

**Comment by maximbilan** [comment]
@xavdid @rhymes Thanks for helping.

I've figured out what there was wrong. Back4App service hasn't version. And the request should be:

`https://parseapi.back4app.com/login...`

So, without '/1/'.
