### ISSUE TITLE
Switch off parse.com

### ISSUE THREAD

**Issue by rhymes** [adelevie/parse-ruby-client#217]
The library by default still connects to Parse.com which does not exist anymore, we should remove it and make passing a host a required thing. See https://github.com/adelevie/parse-ruby-client/blob/master/lib/parse/protocol.rb#L9

We should also replace all references to Parse.com doc in the code to https://parseplatform.github.io/docs/rest/guide/

**Comment by xavdid** [comment]
Nice, yeah. We'll have to make the host a required param since there's no default to fall back to. Good call!

**Comment by rhymes** [comment]
@xavdid Have a look at #220 and let me know :)

**Comment by rhymes** [comment]
Fixed by #220
