### ISSUE TITLE
Does Parse::Cloud::Function.new Still Work?

### ISSUE THREAD

**Issue by OpConTech** [adelevie/parse-ruby-client#224]
Hi, 

Does  Parse::Cloud::Function.new still work? or is there a new syntax like MyClient.cloud?

function = Parse::Cloud::Function.new("inviteNonmemberWEBAPPONLY").call(params[:user])

**Comment by rhymes** [comment]
@OpConTech the syntax is:

```ruby
client.cloud_function('name of the function').call(params)
```

**Comment by OpConTech** [comment]
That was it. 
--- Thank You!
