### ISSUE TITLE
user = User.authenticate stopped working

### ISSUE THREAD

**Issue by OpConTech** [adelevie/parse-ruby-client#225]
Hi @rhymes, 

Been running a Parse Server Heroku app smoothly for quite a while with no recent changes.  IN the last week when authenticating with:
user = User.authenticate(username, password) 
it just stopped returning the User object.

Wondering if you might have any suggestions on things I might of have forgot to check. Heroku and postgres seem to be running normally and there were no changes to the code.

**Comment by rhymes** [comment]
@OpConTech it's hard to know without any error messages or something.

Are you sure nothing has changed? Maybe you updated the Parse server code and it doesn't work anymore?

Did you try to debug?

**Comment by OpConTech** [comment]
Yes did a full debug. The mobile side using iOS Parse SDK working fine. Strictly on the Rails side. Got stuck because have not changed anything on the Parse Server or Rails App in months. So I reached out to see if I might of have overlooked something.

Thanks for trying to help.

On Dec 6, 2017, at 12:07 AM, rhymes <notifications@github.com<mailto:notifications@github.com>> wrote:


@OpConTech<https://github.com/opcontech> it's hard to know without any error messages or something.

Are you sure nothing has changed? Maybe you updated the Parse server code and it doesn't work anymore?

Did you try to debug?

**Comment by OpConTech** [comment]
BTW is it still as per the documetation:
user = Parse::User.authenticate("cooldude6", "p_n7!-e8", client)

or did Parse::User.auth... become just User.auth... ?

**Comment by xavdid** [comment]
@OpConTech Bummer this isn't working as intended. As you can see, we haven't changed anything on this end for quite a while, so it's hard to imagine something here changed. I haven't worked with parse recently, so I'm not sure if something changed on the server itself (if they changed the response to `/login`, then we wouldn't be able to return the user object anymore, for example). I'd look there. 

Sorry we can't be more help!

**Comment by OpConTech** [comment]
Hi Guys, 

I dug deeper and found that it was dropping out because of SSL network failure. It turns out the ExpeditedSSL guys renewed our cert on our Heroku instance for the Parse Server. ExpeditedSSL reported back that the root cause was that they incorrectly installed an intermediate cert.   

Thank you for your replies and helping me troubleshoot.
