### ISSUE TITLE
NoMethodError occuered during retry request.

### ISSUE THREAD

**Issue by kyokutyo** [adelevie/parse-ruby-client#227]
I'm using parse-ruby-client (1.0.0.alpha3) and faraday (0.15.4).
I found `NoMethodError` occurred during retry request.

`sleep_amount` method in Faraday's Request::Retry is removed by [this pull request](https://github.com/lostisland/faraday/pull/773).
Faraday 0.15.0: https://github.com/lostisland/faraday/releases/tag/v0.15.0

With current code base, should version-range of faraday be `['>= 0.9.2', '< 0.15.0']` in `parse-ruby-client.gemspec`?

**Comment by olleolleolle** [comment]
That's a good attempt, could you make an experimental PR?

**Comment by olleolleolle** [comment]
@kyokutyo Thank you for the analysis, I made the suggested change, and it passes the tests, now!
