### ISSUE TITLE
Can you add support for windows 8 push notifications? parse already has

### ISSUE THREAD

**Issue by sunilbg** [adelevie/parse-ruby-client#97]
Is there any support for windows 8 push notifications, if not when is it getting added?

**Comment by Xavdidtheshadow** [comment]
There's not currently a plan for this, but it's worth looking into if they keep the same notification structure for the upcoming Windows 10.

**Comment by rhymes** [comment]
@Xavdidtheshadow is there any documentation on Parse about this?

**Comment by Xavdidtheshadow** [comment]
@rhymes yeah: https://parse.com/tutorials/windows-8-push-tutorial

My concern about putting time on this one is that I get the feeling there's relatively little payoff vs effort required.

**Comment by rhymes** [comment]
@Xavdidtheshadow I agree, I would follow the REST guide as much as possible and that's it :)
